import Provider from '@/context/provider'
import ThemeRegistry from './ThemeRegistry'
import Footer from './components/Footer'
import ResponsiveAppBar from './components/Nav'
import './globals.css'

export const metadata = {
  title: 'Soge',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Provider>
          <ThemeRegistry options={{ key: 'mui' }}>
            <ResponsiveAppBar />
            <main className='w-full h-auto  ' >
              {children}
            </main>
            <Footer />
          </ThemeRegistry>
        </Provider>
      </body>
    </html>
  )
}
